name: 'Delete preview app'
description: 'Delete a Preview app'
author: 'Tapitalee'
inputs:
  tapit-token:
    description: 'Tapit authentication token'
    required: true
  tapit-baseurl:
    description: 'Tapit API'
    required: false
  app_name:
    description: "Name of the Tapitalee app to use, defaults to that app linked to using a deploy token"
    required: false
  preview_app_name:
    description: 'Preview app name to delete'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Tapit CLI
      uses: tapitalee/ghactions/setup-tapit@main
    - name: Set app name from input
      shell: bash
      if: ${{ inputs.app_name != '' }}
      run: echo "TAPIT_APP=${{ inputs.app_name }}" >> $GITHUB_ENV
    - name: Delete app
      shell: bash
      env:
        TAPIT_TOKEN: ${{ inputs.tapit-token }}
        TAPIT_BASEURL: ${{ inputs.tapit-baseurl }}
        DOCKER_TAG: ${{ inputs.docker_tag && inputs.docker_tag || env.GITHUB_SHA_SHORT }}
      run: |
        tapit delete --force preview "${{ inputs.preview_app_name }}"
