name: 'Deploy Image with Tapit'
description: 'Deploys a container image using Tapit CLI'
author: 'Tapitalee'
inputs:
  tapit-token:
    description: 'Tapit authentication token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Tapit CLI
      uses: ./setup-tapit
      
    - name: Get Git SHA
      id: git-sha
      shell: bash
      run: |
        echo "short_sha=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT
        
    - name: Deploy Image
      shell: bash
      env:
        TAPIT_TOKEN: ${{ inputs.tapit-token }}
      run: |
        tapit image deploy tag=${{ steps.git-sha.outputs.short_sha }}
