name: 'Build & Deploy Image with Tapit'
description: 'Builds & deploys a container image using Tapit CLI'
author: 'Tapitalee'
inputs:
  tapit-token:
    description: 'Tapit authentication token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Tapit CLI
      uses: tapitalee/ghactions/setup-tapit@main
      
    - name: Deploy or Create Deploy
      shell: bash
      env:
        TAPIT_TOKEN: ${{ inputs.tapit-token }}
      run: |
        if tapit show image docker_tag="${GITHUB_SHA::16}" ; then
          echo "Image exists, creating deploy..."
          tapit create deploy docker_tag="${GITHUB_SHA::16}" tag="${{ github.head_ref || github.ref_name }}" git_hash="${{ github.sha }}" initiator="${{ github.triggering_actor }}"
        else
          echo "Image does not exist, deploying image..."
          tapit image deploy docker_tag="${GITHUB_SHA::16}" tag="${{ github.head_ref || github.ref_name }}" git_hash="${{ github.sha }}" initiator="${{ github.triggering_actor }}"
        fi
    - name: Create deploy summary
      shell: bash
      run: |
        echo "### 🚀 Tapit Image Deploy Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Tag**: ${{ github.head_ref || github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Git Hash**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Initiator**: ${{ github.triggering_actor }}" >> $GITHUB_STEP_SUMMARY
