name: 'Build & Deploy Image with Tapit'
description: 'Builds & deploys a container image using Tapit CLI'
author: 'Tapitalee'
inputs:
  tapit-token:
    description: 'Tapit authentication token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Tapit CLI
      uses: tapitalee/ghactions/setup-tapit@main
      
    - name: Deploy Image
      shell: bash
      env:
        TAPIT_TOKEN: ${{ inputs.tapit-token }}
      run: |
        tapit image deploy tag="${{ github.ref_name }}" git_hash="${{ github.sha }}" initiator="${{ github.triggering_actor }}"

    - name: Create deploy summary
      shell: bash
      run: |
        echo "### 🚀 Tapit Image Deploy Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Tag**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Git Hash**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Initiator**: ${{ github.triggering_actor }}" >> $GITHUB_STEP_SUMMARY
