name: 'Build & Deploy Image with Tapit'
description: 'Builds & deploys a container image using Tapit CLI'
author: 'Tapitalee'
inputs:
  tapit-token:
    description: 'Tapit authentication token'
    required: true
  tapit-baseurl:
    description: 'Tapit API'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup Tapit CLI
      uses: tapitalee/ghactions/setup-tapit@main
      
    - name: Deploy Image
      shell: bash
      env:
        TAPIT_TOKEN: ${{ inputs.tapit-token }}
        TAPIT_BASEURL: ${{ inputs.tapit-baseurl }}
      run: |
        tapit image deploy docker_tag="${GITHUB_SHA::16}" tag="${{ github.head_ref || github.ref_name }}" git_hash="${{ github.sha }}" initiator="${{ github.triggering_actor }}"
    - name: Create deploy summary
      shell: bash
      run: |
        echo "### 🚀 Tapit Image Deploy Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Tag**: ${{ github.head_ref || github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Docker Tag**: ${GITHUB_SHA::16}" >> $GITHUB_STEP_SUMMARY
        echo "- **Initiator**: ${{ github.triggering_actor }}" >> $GITHUB_STEP_SUMMARY
