name: 'Build & Deploy Image with Tapit'
description: 'Builds & deploys a container image using Tapit CLI'
author: 'Tapitalee'
inputs:
  tapit-token:
    description: 'Tapit authentication token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Tapit CLI
      uses: tapitalee/ghactions/setup-tapit@main
      
    - name: Deploy Image
      shell: bash
      env:
        TAPIT_TOKEN: ${{ inputs.tapit-token }}
      run: |
        tapit image deploy tag="${{ github.ref_name }}" git_hash="${{ github.sha }}" initiator="${{ github.triggering_actor }}"
