name: 'Create Preview app'
description: 'Create a Preview app'
author: 'Tapitalee'
inputs:
  tapit-token:
    description: 'Tapit authentication token'
    required: true
  tapit-baseurl:
    description: 'Tapit API'
    required: false
  preview_app_name:
    description: 'Preview app name'
    required: true
  delete_in_days:
    description: 'Expire (delete) app after this many days'
    required: false
  app_name:
    description: "Name of the Tapitalee app to use, defaults to that app linked to using a deploy token"
    required: false
  domain:
    description: "Optional domain name to attach to preview app"
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup Tapit CLI
      uses: tapitalee/ghactions/setup-tapit@main
    - name: Set app name from input
      shell: bash
      if: ${{ inputs.app_name != '' }}
      run: echo "TAPIT_APP=${{ inputs.app_name }}" >> $GITHUB_ENV
    - name: Set short SHA
      id: sha
      shell: bash
      run: echo "GITHUB_SHA_SHORT=${GITHUB_SHA::16}" >> $GITHUB_ENV
    - name: Create Preview app
      shell: bash
      env:
        TAPIT_TOKEN: ${{ inputs.tapit-token }}
        TAPIT_BASEURL: ${{ inputs.tapit-baseurl }}
        DOCKER_TAG: ${{ inputs.docker_tag && inputs.docker_tag || env.GITHUB_SHA_SHORT }}
      run: |
        tapit create preview "${{ inputs.preview_app_name }}" delete_in_days="${{ inputs.delete_in_days }}" domain="${{ inputs.domain }}" --wait
        echo "hostname=${{ inputs.domain }}" >> "$GITHUB_OUTPUT"
