name: 'Create Task with Tapit'
description: 'Create background task using Tapit CLI'
author: 'Tapitalee'
inputs:
  tapit-token:
    description: 'Tapit authentication token'
    required: true
  background:
    description: 'Run task in background (adds --wait if false)'
    required: false
    default: 'true'
  memory:
    description: 'Memory allocation in GB'
    required: false
    default: '2'
  cpu:
    description: 'CPU allocation in cores'
    required: false
    default: '0.25'

runs:
  using: 'composite'
  steps:
    - name: Setup Tapit CLI
      uses: tapitalee/ghactions/setup-tapit@main
      
    - name: Create Task
      shell: bash
      env:
        TAPIT_TOKEN: ${{ inputs.tapit-token }}
      run: |
        tapit create task tag="${{ github.ref_name }}" git_hash="${{ github.sha }}" ${{ inputs.background == 'false' && '--wait' || '' }} memory=${{ inputs.memory }} cpu=${{ inputs.cpu }}
