name: 'Create Task with Tapit'
description: 'Create background task using Tapit CLI'
author: 'Tapitalee'
inputs:
  tapit-token:
    description: 'Tapit authentication token'
    required: true
  command:
    description: 'Command'
    required: true
  memory:
    description: 'Memory allocation in GB'
    required: false
    default: '2'
  cpu:
    description: 'CPU allocation in cores'
    required: false
    default: '0.25'

runs:
  using: 'composite'
  steps:
    - name: Setup Tapit CLI
      uses: tapitalee/ghactions/setup-tapit@main
      
    - name: Create Task
      shell: bash
      env:
        TAPIT_TOKEN: ${{ inputs.tapit-token }}
      run: |
        tapit create task "${{ inputs.command }}" docker_tag="${GITHUB_SHA::16}" memory="${{ inputs.memory }}" cpu="${{ inputs.cpu }}" initiator="${{ github.triggering_actor }}" -w
